.PHONY: clean All

All:
	@echo "----------Building project:[ Almacen - Debug ]----------"
	@cd "Almacen" && "$(MAKE)" -f  "Almacen.mk"
clean:
	@echo "----------Cleaning project:[ Almacen - Debug ]----------"
	@cd "Almacen" && "$(MAKE)" -f  "Almacen.mk" clean
