.PHONY: clean All

All:
	@echo "----------Building project:[ FINAL - Debug ]----------"
	@cd "FINAL" && "$(MAKE)" -f  "FINAL.mk"
clean:
	@echo "----------Cleaning project:[ FINAL - Debug ]----------"
	@cd "FINAL" && "$(MAKE)" -f  "FINAL.mk" clean
